//! Parity tests: compare rage-extractor output against librosa reference data.
//!
//! Reference data is generated by `scripts/parity/generate_reference.py`
//! and stored in `tests/fixtures/parity/`.
//!
//! Run with: cargo test --test parity

use ndarray::Array2;
use rage_core::ExtractionConfig;
use std::path::PathBuf;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("tests")
        .join("fixtures")
        .join("parity")
}

/// Load a raw f32 little-endian binary file and its JSON metadata into an Array2.
fn load_reference(name: &str) -> Array2<f32> {
    let dir = fixtures_dir();
    let bin_path = dir.join(format!("{name}.bin"));
    let meta_path = dir.join(format!("{name}.json"));

    let meta: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(&meta_path)
            .unwrap_or_else(|e| panic!("Failed to read {}: {e}", meta_path.display())),
    )
    .unwrap();

    let shape: Vec<usize> = meta["shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect();

    let bytes = std::fs::read(&bin_path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {e}", bin_path.display()));

    let floats: Vec<f32> = bytes
        .chunks_exact(4)
        .map(|chunk| f32::from_le_bytes(chunk.try_into().unwrap()))
        .collect();

    assert_eq!(
        floats.len(),
        shape.iter().product::<usize>(),
        "Shape mismatch for {name}: {} floats but shape {shape:?}",
        floats.len()
    );

    Array2::from_shape_vec((shape[0], shape[1]), floats).unwrap()
}

/// Load raw f32 audio samples from a binary file.
fn load_audio_samples(name: &str) -> Vec<f32> {
    let dir = fixtures_dir();
    let bin_path = dir.join(format!("{name}_audio.bin"));

    let bytes = std::fs::read(&bin_path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {e}", bin_path.display()));

    bytes
        .chunks_exact(4)
        .map(|chunk| f32::from_le_bytes(chunk.try_into().unwrap()))
        .collect()
}

/// Compare two Array2<f32> using relative tolerance for large values
/// and absolute tolerance for small values.
///
/// Uses the formula: |rust - ref| <= atol + rtol * |ref|
/// This matches numpy's allclose behavior.
fn assert_arrays_close(
    name: &str,
    rust: &Array2<f32>,
    reference: &Array2<f32>,
    atol: f32,
    rtol: f32,
) {
    assert_eq!(
        rust.shape(),
        reference.shape(),
        "{name}: shape mismatch: rust={:?} vs reference={:?}",
        rust.shape(),
        reference.shape()
    );

    let mut max_rel_err: f64 = 0.0;
    let mut max_rel_pos = (0, 0);
    let mut max_abs_err: f32 = 0.0;
    let mut max_abs_pos = (0, 0);
    let mut n_exceed = 0usize;
    let n = rust.len();

    for ((r, c), rust_val) in rust.indexed_iter() {
        let ref_val = reference[[r, c]];
        let abs_err = (rust_val - ref_val).abs();
        let tol = atol + rtol * ref_val.abs();

        if abs_err > max_abs_err {
            max_abs_err = abs_err;
            max_abs_pos = (r, c);
        }

        let rel = if ref_val.abs() > 1e-10 {
            abs_err as f64 / ref_val.abs() as f64
        } else {
            abs_err as f64
        };
        if rel > max_rel_err {
            max_rel_err = rel;
            max_rel_pos = (r, c);
        }

        if abs_err > tol {
            n_exceed += 1;
        }
    }

    println!(
        "  {name}: max_abs_err={max_abs_err:.6} at {:?}, max_rel_err={max_rel_err:.2e} at {:?}, shape={:?}",
        max_abs_pos, max_rel_pos, rust.shape()
    );

    assert_eq!(
        n_exceed, 0,
        "{name}: {n_exceed}/{n} elements exceed tolerance (atol={atol}, rtol={rtol}). \
         Worst abs_err={max_abs_err:.6} at {:?} (rust={:.6}, ref={:.6})",
        max_abs_pos,
        rust[max_abs_pos],
        reference[max_abs_pos]
    );
}

/// Tolerances:
///  - atol: absolute tolerance (dominates for small values)
///  - rtol: relative tolerance (dominates for large values)
///  Combined: |err| <= atol + rtol * |ref|
const RTOL: f32 = 1e-4;

fn run_parity_test(signal_name: &str) {
    let config = ExtractionConfig::default();

    println!("\n=== Parity test: {signal_name} ===");

    let samples = load_audio_samples(signal_name);
    println!("  Audio: {} samples", samples.len());

    // STFT magnitude
    let rust_stft = rage_extractor::stft::stft_magnitude(&samples, config.n_fft, config.hop_length);
    let ref_stft = load_reference(&format!("{signal_name}_stft_magnitude"));
    assert_arrays_close("STFT magnitude", &rust_stft, &ref_stft, 1e-4, RTOL);

    // Power spectrum (squared magnitudes amplify absolute error, but relative error stays small)
    let rust_power = rage_extractor::stft::power_spectrum(&rust_stft);
    let ref_power = load_reference(&format!("{signal_name}_power_spectrum"));
    assert_arrays_close("Power spectrum", &rust_power, &ref_power, 1e-4, RTOL);

    // Mel filterbank (config-derived, not signal-dependent)
    let rust_mel_fb = rage_extractor::mel::mel_filterbank(&config);
    let ref_mel_fb = load_reference(&format!("{signal_name}_mel_filterbank"));
    assert_arrays_close("Mel filterbank", &rust_mel_fb, &ref_mel_fb, 1e-6, RTOL);

    // Mel spectrogram
    let rust_mel = rage_extractor::mel::mel_spectrogram(&rust_power, &config);
    let ref_mel = load_reference(&format!("{signal_name}_mel_spectrogram"));
    assert_arrays_close("Mel spectrogram", &rust_mel, &ref_mel, 1e-3, RTOL);

    // Log-mel spectrogram (the actual CNN input — most important to match)
    let rust_log_mel = rage_extractor::mel::power_to_db(&rust_mel);
    let ref_log_mel = load_reference(&format!("{signal_name}_log_mel_spectrogram"));
    assert_arrays_close("Log-mel spectrogram", &rust_log_mel, &ref_log_mel, 0.01, RTOL);
}

#[test]
fn parity_sine_440() {
    run_parity_test("sine_440");
}

#[test]
fn parity_chirp() {
    run_parity_test("chirp");
}

#[test]
fn parity_silence() {
    run_parity_test("silence");
}
