use serde::{Deserialize, Serialize};

/// The 56 mood/theme tags from the MTG-Jamendo dataset.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MoodTag {
    Action,
    Adventure,
    Advertising,
    Amusing,
    Angry,
    Background,
    Ballad,
    Calm,
    Children,
    Christmas,
    Commercial,
    Cool,
    Corporate,
    Dark,
    Deep,
    Documentary,
    Drama,
    Dreamy,
    Emotional,
    Energetic,
    Epic,
    Fast,
    Film,
    Fun,
    Funny,
    Game,
    Groovy,
    Happy,
    Heavy,
    Holiday,
    Hopeful,
    Inspiring,
    Love,
    Meditative,
    Melancholic,
    Melodic,
    Motivational,
    Movie,
    Nature,
    Party,
    Positive,
    Powerful,
    Relaxing,
    Retro,
    Romantic,
    Sad,
    Sexy,
    Slow,
    Soft,
    Soundscape,
    Space,
    Sport,
    Summer,
    Trailer,
    Travel,
    Uplifting,
}

impl MoodTag {
    /// All 56 tags in order (matches the model output index).
    pub const ALL: [MoodTag; 56] = [
        MoodTag::Action,
        MoodTag::Adventure,
        MoodTag::Advertising,
        MoodTag::Amusing,
        MoodTag::Angry,
        MoodTag::Background,
        MoodTag::Ballad,
        MoodTag::Calm,
        MoodTag::Children,
        MoodTag::Christmas,
        MoodTag::Commercial,
        MoodTag::Cool,
        MoodTag::Corporate,
        MoodTag::Dark,
        MoodTag::Deep,
        MoodTag::Documentary,
        MoodTag::Drama,
        MoodTag::Dreamy,
        MoodTag::Emotional,
        MoodTag::Energetic,
        MoodTag::Epic,
        MoodTag::Fast,
        MoodTag::Film,
        MoodTag::Fun,
        MoodTag::Funny,
        MoodTag::Game,
        MoodTag::Groovy,
        MoodTag::Happy,
        MoodTag::Heavy,
        MoodTag::Holiday,
        MoodTag::Hopeful,
        MoodTag::Inspiring,
        MoodTag::Love,
        MoodTag::Meditative,
        MoodTag::Melancholic,
        MoodTag::Melodic,
        MoodTag::Motivational,
        MoodTag::Movie,
        MoodTag::Nature,
        MoodTag::Party,
        MoodTag::Positive,
        MoodTag::Powerful,
        MoodTag::Relaxing,
        MoodTag::Retro,
        MoodTag::Romantic,
        MoodTag::Sad,
        MoodTag::Sexy,
        MoodTag::Slow,
        MoodTag::Soft,
        MoodTag::Soundscape,
        MoodTag::Space,
        MoodTag::Sport,
        MoodTag::Summer,
        MoodTag::Trailer,
        MoodTag::Travel,
        MoodTag::Uplifting,
    ];

    /// Returns the index of this tag in the model output vector.
    pub fn index(self) -> usize {
        Self::ALL.iter().position(|&t| t == self).unwrap()
    }

    /// Returns the display name of this tag.
    pub fn name(self) -> &'static str {
        match self {
            MoodTag::Action => "action",
            MoodTag::Adventure => "adventure",
            MoodTag::Advertising => "advertising",
            MoodTag::Amusing => "amusing",
            MoodTag::Angry => "angry",
            MoodTag::Background => "background",
            MoodTag::Ballad => "ballad",
            MoodTag::Calm => "calm",
            MoodTag::Children => "children",
            MoodTag::Christmas => "christmas",
            MoodTag::Commercial => "commercial",
            MoodTag::Cool => "cool",
            MoodTag::Corporate => "corporate",
            MoodTag::Dark => "dark",
            MoodTag::Deep => "deep",
            MoodTag::Documentary => "documentary",
            MoodTag::Drama => "drama",
            MoodTag::Dreamy => "dreamy",
            MoodTag::Emotional => "emotional",
            MoodTag::Energetic => "energetic",
            MoodTag::Epic => "epic",
            MoodTag::Fast => "fast",
            MoodTag::Film => "film",
            MoodTag::Fun => "fun",
            MoodTag::Funny => "funny",
            MoodTag::Game => "game",
            MoodTag::Groovy => "groovy",
            MoodTag::Happy => "happy",
            MoodTag::Heavy => "heavy",
            MoodTag::Holiday => "holiday",
            MoodTag::Hopeful => "hopeful",
            MoodTag::Inspiring => "inspiring",
            MoodTag::Love => "love",
            MoodTag::Meditative => "meditative",
            MoodTag::Melancholic => "melancholic",
            MoodTag::Melodic => "melodic",
            MoodTag::Motivational => "motivational",
            MoodTag::Movie => "movie",
            MoodTag::Nature => "nature",
            MoodTag::Party => "party",
            MoodTag::Positive => "positive",
            MoodTag::Powerful => "powerful",
            MoodTag::Relaxing => "relaxing",
            MoodTag::Retro => "retro",
            MoodTag::Romantic => "romantic",
            MoodTag::Sad => "sad",
            MoodTag::Sexy => "sexy",
            MoodTag::Slow => "slow",
            MoodTag::Soft => "soft",
            MoodTag::Soundscape => "soundscape",
            MoodTag::Space => "space",
            MoodTag::Sport => "sport",
            MoodTag::Summer => "summer",
            MoodTag::Trailer => "trailer",
            MoodTag::Travel => "travel",
            MoodTag::Uplifting => "uplifting",
        }
    }
}

impl std::fmt::Display for MoodTag {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.name())
    }
}
